Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
]

#comprobamos si estamos en debug y agregamos el url pattern de archivos estaticos
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Blog/Home/urls.py
from django.urls import path
from .views import HomeListView, HomeDetailView

app_name = 'home'

urlpatterns = [
    path('', HomeListView.as_view(), name='list'),
    path('post/<pk>', HomeDetailView.as_view(), name='detail'),
]

Blog/Home/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.db.models.fields import CharField


class Category(models.Model):
    name = models.CharField('Nombre de Categoria', max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_at']


class Post(models.Model):
    title = models.CharField('Titulo', max_length=50)
    description = models.TextField(max_length=200)
    content = RichTextField('Contenido')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


class Comment(models.Model):
    title = models.CharField('Titulo del comentario', max_length=20)
    content = models.CharField('Comentario', max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

Blog/Home/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['title', 'content']
        labels = {
            'title': '',
            'content': '',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'Titulo del mensaje',
                    'class': 'form-control'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'placeholder': 'Escribe aqui tu comentario...',
                    'class': 'form-control',
                    'rows': 4
                }
            )
        }

Blog/Home/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import FormMixin
from .models import Category, Post, Comment
from .forms import CommentForm


class HomeListView(ListView):
    template_name = "home/post_list.html"
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        kword = self.request.GET.get("kword")
        category = self.request.GET.get("category")

        if category:
            queryset = Post.objects.filter(category__name=category)
        
        if kword:
            queryset = Post.objects.filter(
                Q(title__icontains=kword) | Q(content__icontains=kword)
            )

        return queryset


class HomeDetailView(FormMixin, DetailView):
    model = Post
    template_name = "home/post_detail.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.object.comment_set.all()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()        
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.post = self.object
        obj.created_by = self.request.user
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.path

Blog/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Simple - {% block title %}{% endblock title %}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <button class="navbar-toggler my-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="{% url 'home:list' %}">Blog Simple</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <form class="d-flex" method="GET" action="{% url 'home:list' %}">
              <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search" name="kword">
              <button class="btn btn-outline-secondary" type="submit">Buscar</button>
            </form>
          </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    
 
    {% bootstrap_javascript %}
</body>
</html>

Blog/templates/home/nav.html
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link link-secondary" href="{% url 'home:list' %}">Posts</a>
    </li>
    {% for category in categories %}  
        <li class="nav-item">
            <a class="nav-link link-secondary" href="{% url 'home:list' %}?category={{category.name}}">{{category.name}}</a>
        </li>
    {% endfor %}
</ul>

Blog/templates/home/post_detail.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header">
            <h3 class="mb-0">{{post.title}}</h3>
        </div>
        <div class="card-body">
            {{post.content|safe}}
        </div>
    </div>
        
    <h3 class="mt-4">Comentarios</h3>
    <hr> 

    {% for comment in comments %}
        <p><strong>{{comment.created_by}} ({{comment.created_at}}):</strong></p>
        <p>{{comment.title}}</p>
        <p>{{comment.content}}</p>
        <hr>
    {% endfor %}
        
    {% if user.is_authenticated %}
        <form method="POST">
        <div class="form-group mb-4">
            {% csrf_token %}
            {{form.as_p}}
            <button class="form-control btn btn-secondary" type="submit">Comentar</button>
        </div>
    </form>
    {% else %}
        <p>Logueate para dejar tu comentario!</p>
    {% endif %}

{% endblock content %}

Blog/templates/home/post_list.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% load bootstrap_icons %}

{% block content %} 
    <div class="row"> 
        {% include 'home/nav.html' %}             
        {% for post in posts %}   
            <div class="col-sm-6 mt-4">

                <div class="card h-100">
                    <h5 class="card-header">{{post.title}}</h5>
                    <div class="card-body d-flex flex-column">
                        <p class="card-text">
                            {% if post.description|length > 200 %}
                                {{post.description|slice:200}}...
                            {% else %}
                                {{post.description}}
                            {% endif %} 
                        </p>
                        <a href="{% url 'home:detail' post.id %}" class="btn btn-sm btn-outline-secondary align-self-start mt-auto">Continuar leyendo</a>
                    </div>
                </div>
                
            </div>
        {% empty %}
            <p class="text-secondary mt-3">Nada que mostrar...</p>
        {% endfor %}
    </div>

    {% if is_paginated %}
        <div>   
            <ul class="pagination pagination-sm justify-content-center mt-4 mb-0">
                
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            {% bs_icon 'arrow-left' extra_classes="link-secondary" %}
                        </a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">{{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            {% bs_icon 'arrow-right' extra_classes="link-secondary" %}
                        </a>
                    </li>     
                {% endif %}

            </ul>
        </div>
{% endif %}

{% endblock content %}
 